#ifndef LIBDSTEPWMXCB_GLOBAL_H
#define LIBDSTEPWMXCB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBDSTEPWMXCB_LIBRARY)
#  define LIBDSTEPWMXCBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBDSTEPWMXCBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBDSTEPWMXCB_GLOBAL_H
