#ifndef LIBDSTEPSHELL_GLOBAL_H
#define LIBDSTEPSHELL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBDSTEPSHELL_LIBRARY)
#  define LIBDSTEPSHELLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBDSTEPSHELLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBDSTEPSHELL_GLOBAL_H
