#ifndef LIBDSTEPCOMMON_GLOBAL_H
#define LIBDSTEPCOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBDSTEPCOMMON_LIBRARY)
#  define LIBDSTEPCOMMONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBDSTEPCOMMONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBDSTEPCOMMON_GLOBAL_H
